<a href="https://colab.research.google.com/github/AmbarishBorah/AmbarishBorah.github.io/blob/master/nb/Qwen2.5_(3B)-GRPO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

To run this, press "*Runtime*" and press "*Run all*" on a **free** Tesla T4 Google Colab instance!
<div class="align-center">
<a href="https://unsloth.ai/"><img src="https://github.com/unslothai/unsloth/raw/main/images/unsloth%20new%20logo.png" width="115"></a>
<a href="https://discord.gg/unsloth"><img src="https://github.com/unslothai/unsloth/raw/main/images/Discord button.png" width="145"></a>
<a href="https://unsloth.ai/docs/"><img src="https://github.com/unslothai/unsloth/blob/main/images/documentation%20green%20button.png?raw=true" width="125"></a> Join Discord if you need help + ⭐ <i>Star us on <a href="https://github.com/unslothai/unsloth">Github</a> </i> ⭐
</div>

To install Unsloth on your local device, follow [our guide](https://unsloth.ai/docs/get-started/install). This notebook is licensed [LGPL-3.0](https://github.com/unslothai/notebooks?tab=LGPL-3.0-1-ov-file#readme).

You will learn how to do [data prep](#Data), how to [train](#Train), how to [run the model](#Inference), & how to save it

### News

Introducing **[Unsloth Desktop](https://unsloth.ai/docs/desktop)**, the first desktop app to run and train models. Free and open-source for macOS, Windows and Linux. [GitHub](https://github.com/unslothai/unsloth) • [Download](https://unsloth.ai/download)

<p>
<a href="https://unsloth.ai/docs/desktop"><img src="https://raw.githubusercontent.com/unslothai/notebooks/refs/heads/main/assets/unsloth-qwen3-8.png" width="350" alt="Introducing Unsloth Desktop"></a>
</p>

Train MoEs - DeepSeek, GLM, Qwen and gpt-oss 12x faster with 35% less VRAM. [Blog](https://unsloth.ai/docs/new/faster-moe)

Ultra Long-Context Reinforcement Learning is here with 7x more context windows! [Blog](https://unsloth.ai/docs/new/grpo-long-context)

New in Reinforcement Learning: [FP8 RL](https://unsloth.ai/docs/new/fp8-reinforcement-learning) • [Vision RL](https://unsloth.ai/docs/new/vision-reinforcement-learning-vlm-rl) • [Standby](https://unsloth.ai/docs/basics/memory-efficient-rl) • [gpt-oss RL](https://unsloth.ai/docs/new/gpt-oss-reinforcement-learning)

Visit our docs for all our [model uploads](https://unsloth.ai/docs/get-started/unsloth-model-catalog) and [notebooks](https://unsloth.ai/docs/get-started/unsloth-notebooks).

### Installation

In [ ]:
%%capture
import os
os.environ["UNSLOTH_VLLM_STANDBY"] = "1" # [NEW] Extra 30% context lengths!
if "COLAB_" not in "".join(os.environ.keys()):
    # If you're not in Colab, just use pip install or uv pip install
    !pip install unsloth vllm
else:
    pass # For Colab / Kaggle, we need extra instructions hidden below \/

In [ ]:
#@title Colab Extra Install { display-mode: "form" }
%%capture
import os
!pip install --upgrade -qqq uv
if "COLAB_" not in "".join(os.environ.keys()):
    # If you're not in Colab, just use pip install!
    !pip install unsloth vllm
else:
    try: import numpy, PIL; _numpy = f'numpy=={numpy.__version__}'; _pil = f'pillow=={PIL.__version__}'
    except: _numpy = "numpy"; _pil = "pillow"
    try: import subprocess; is_t4 = "Tesla T4" in str(subprocess.check_output(["nvidia-smi"]))
    except: is_t4 = False
    _vllm, _triton = ('vllm==0.11.2', 'triton') if is_t4 else ('vllm==0.15.1', 'triton')
    !uv pip install -qqq --upgrade {_vllm} {_numpy} {_pil} torchvision bitsandbytes xformers unsloth
    !uv pip install -qqq {_triton}
    try:
        import importlib.metadata as _md; _torch_v = tuple(int(_p) for _p in _md.version("torch").split("+")[0].split(".")[:2])
    except Exception:
        _torch_v = ()
    # torchao 0.18.0 imports torch.nn.functional.ScalingType, added in torch 2.10; peft >= 0.19 needs the 0.16.0 floor.
    _torchao = "torchao>=0.16.0" if _torch_v >= (2, 10) else "torchao>=0.16.0,<0.18.0"
    !uv pip install -qqq --no-deps --upgrade "{_torchao}"
!uv pip install transformers==4.57.6
!uv pip install --no-deps trl==0.22.2

### Unsloth

Load up `Qwen 2.5 3B Instruct`, and set parameters

In [3]:
from unsloth import FastLanguageModel, is_bfloat16_supported
import torch
max_seq_length = 1024 # Can increase for longer reasoning traces
lora_rank = 64 # Larger rank = smarter, but slower

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "unsloth/Qwen2.5-3B-Instruct",
    max_seq_length = max_seq_length,
    load_in_4bit = True, # False for LoRA 16bit
    fast_inference = True, # Enable vllm fast inference
    max_lora_rank = lora_rank,
    gpu_memory_utilization = 0.9, # Reduce if out of memory
)

model = FastLanguageModel.get_peft_model(
    model,
    r = lora_rank, # Choose any number > 0 ! Suggested 8, 16, 32, 64, 128
    target_modules = [
        "q_proj", "k_proj", "v_proj", "o_proj",
        "gate_proj", "up_proj", "down_proj",
    ], # Remove QKVO if out of memory
    lora_alpha = lora_rank,
    use_gradient_checkpointing = "unsloth", # Enable long context finetuning
    random_state = 3407,
)

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.

/usr/local/lib/python3.13/dist-packages/unsloth/_gpu_init.py:450: UserWarning: Unsloth: torchcodec is installed but cannot load its native libraries although FFmpeg is on the loader path; likely an FFmpeg major it does not support (it takes 4 to 8), a missing CUDA NPP runtime (nvidia-npp), or a build that does not match this torch; audio datasets decode through soundfile and PyAV instead (wav/flac/mp3/ogg, m4a/aac/webm). torchcodec 0.11.0+cu130 is incompatible with torch 2.9.0+cu128; install a matching build with `pip install --index-url https://download.pytorch.org/whl/cu128 'torchcodec>=0.9,<0.10.0'`.
  disable_torchcodec_if_broken()

ERROR 10-09 10:35:24 [fa_utils.py:64] Cannot use FA version 2 is not supported due to FA2 is only supported on devices with compute capability >= 8
🦥 Unsloth Zoo will now patch everything to make training faster!
INFO 10-09 10:35:54 [vllm_utils.py:836] Unsloth: Patching vLLM v1 graph capture
==((====))==  Unsloth 2026.10.3: Fast Qwen2 patching. Transformers: 4.57.6. vLLM: 0.11.2.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.9.0+cu128. CUDA: 7.5. CUDA Toolkit: 12.8. Triton: 3.5.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.33.post1. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
Unsloth: Not planning a device map; vLLM places its own weights. Using `sequential`.
Unsloth: Standby mode is enabled. However your setting of `gpu_memory_utilization` will OOM.
Changing `gpu_memory_utilization` to 0.76.
Unsloth: Not an error, but `use_cudagraph` is not supported in vLLM.config.CompilationConfig. Skipping.
WARNING 10-09 10:36:40 [compilation.py:610] Level is deprecated and will be removed in the next release,either 0.12.0 or 0.11.2 whichever is soonest.Use mode instead.If both level and mode are given,only mode will be used.
WARNING 10-09 10:36:40 [compilation.py:699] The 'use_inductor' flag is deprecated and will be removed in the next release (v0.12.0). Please use the 'backend' option instead.
Unsloth: Not an error, but `device` is not supported in vLLM. Skipping.
Unsloth: vLLM loading unsloth/Qwen2.5-3B-Instruct-unsloth-bnb-4bit with actual GPU utilization = 74.93%
Unsloth: Your GPU has CUDA compute capability 7.5 with VRAM = 14.56 GB.
Unsloth: Using conservativeness = 1.0. Chunked prefill tokens = 4096. Num Sequences = 48.
Unsloth: vLLM's KV Cache can use up to 8.08 GB. Also swap space = 0 GB.
INFO 10-09 10:36:40 [utils.py:253] non-default args: {'load_format': 'bitsandbytes', 'dtype': torch.float16, 'seed': 0, 'max_model_len': 1024, 'enable_prefix_caching': True, 'swap_space': 0, 'gpu_memory_utilization': 0.7492531108158741, 'max_num_batched_tokens': 4096, 'max_num_seqs': 48, 'max_logprobs': 0, 'logprobs_mode': 'processed_logprobs', 'disable_log_stats': True, 'quantization': 'bitsandbytes', 'enable_lora': True, 'max_lora_rank': 64, 'enable_chunked_prefill': True, 'compilation_config': {'level': 3, 'mode': 3, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': [], 'splitting_ops': None, 'compile_mm_encoder': False, 'use_inductor': True, 'compile_sizes': None, 'inductor_compile_config': {'epilogue_fusion': True, 'max_autotune': False, 'shape_padding': True, 'trace.enabled': False, 'triton.cudagraphs': False, 'debug': False, 'dce': True, 'memory_planning': True, 'coordinate_descent_tuning': False, 'trace.graph_diagram': False, 'compile_threads': 4, 'group_fusion': True, 'disable_progress': False, 'verbose_progress': True, 'triton.multi_kernel': 0, 'triton.use_block_ptr': True, 'triton.enable_persistent_tma_matmul': True, 'triton.autotune_at_compile_time': False, 'triton.cooperative_reductions': False, 'cuda.compile_opt_level': '-O2', 'cuda.enable_cuda_lto': True, 'combo_kernels': False, 'benchmark_combo_kernel': True, 'combo_kernel_foreach_dynamic_shapes': True, 'enable_auto_functionalized_v2': False}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': None, 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {}, 'max_cudagraph_capture_size': None, 'local_cache_dir': None}, 'enable_sleep_mode': True, 'model': 'unsloth/Qwen2.5-3B-Instruct-unsloth-bnb-4bit'}

/usr/local/lib/python3.13/dist-packages/pydantic/type_adapter.py:581: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `enum` - serialized value may not be as expected [field_name='mode', input_value=3, input_type=int])
  return self.serializer.to_python(

INFO 10-09 10:36:55 [model.py:631] Resolved architecture: Qwen2ForCausalLM
WARNING 10-09 10:36:55 [model.py:1971] Casting torch.bfloat16 to torch.float16.
INFO 10-09 10:36:55 [model.py:1745] Using max model len 1024
INFO 10-09 10:36:58 [scheduler.py:216] Chunked prefill is enabled with max_num_batched_tokens=4096.
Unsloth: vLLM Bitsandbytes config using kwargs = {'load_in_8bit': False, 'load_in_4bit': True, 'bnb_4bit_compute_dtype': 'float16', 'bnb_4bit_quant_storage': 'uint8', 'bnb_4bit_quant_type': 'nf4', 'bnb_4bit_use_double_quant': True, 'llm_int8_enable_fp32_cpu_offload': False, 'llm_int8_has_fp16_weight': False, 'llm_int8_skip_modules': ['lm_head', 'multi_modal_projector', 'merger', 'modality_projection', 'model.layers.2.mlp', 'model.layers.3.mlp', 'model.layers.30.mlp'], 'llm_int8_threshold': 6.0}

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json:   0%|          | 0.00/11.4M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/605 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/614 [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/271 [00:00<?, ?B/s]

INFO 10-09 10:37:04 [core.py:93] Initializing a V1 LLM engine (v0.11.2) with config: model='unsloth/Qwen2.5-3B-Instruct-unsloth-bnb-4bit', speculative_config=None, tokenizer='unsloth/Qwen2.5-3B-Instruct-unsloth-bnb-4bit', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=1024, download_dir=None, load_format=bitsandbytes, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=False, quantization=bitsandbytes, enforce_eager=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=unsloth/Qwen2.5-3B-Instruct-unsloth-bnb-4bit, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'level': 3, 'mode': 3, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['none'], 'splitting_ops': ['vllm::unified_attention', 'vllm::unified_attention_with_output', 'vllm::unified_mla_attention', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::kda_attention', 'vllm::sparse_attn_indexer'], 'compile_mm_encoder': False, 'use_inductor': True, 'compile_sizes': [], 'inductor_compile_config': {'epilogue_fusion': True, 'max_autotune': False, 'shape_padding': True, 'trace.enabled': False, 'triton.cudagraphs': False, 'debug': False, 'dce': True, 'memory_planning': True, 'coordinate_descent_tuning': False, 'trace.graph_diagram': False, 'compile_threads': 4, 'group_fusion': True, 'disable_progress': False, 'verbose_progress': True, 'triton.multi_kernel': 0, 'triton.use_block_ptr': True, 'triton.enable_persistent_tma_matmul': True, 'triton.autotune_at_compile_time': False, 'triton.cooperative_reductions': False, 'cuda.compile_opt_level': '-O2', 'cuda.enable_cuda_lto': True, 'combo_kernels': False, 'benchmark_combo_kernel': True, 'combo_kernel_foreach_dynamic_shapes': True, 'enable_auto_functionalized_v2': False}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_AND_PIECEWISE: (2, 1)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1, 2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {}, 'max_cudagraph_capture_size': 96, 'local_cache_dir': None}
INFO 10-09 10:37:04 [parallel_state.py:1208] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://172.28.0.12:56675 backend=nccl
INFO 10-09 10:37:04 [parallel_state.py:1394] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0

/usr/local/lib/python3.13/dist-packages/pydantic/type_adapter.py:581: UserWarning: Pydantic serializer warnings:
  PydanticSerializationUnexpectedValue(Expected `enum` - serialized value may not be as expected [field_name='mode', input_value=3, input_type=int])
  return self.serializer.to_python(

INFO 10-09 10:37:05 [gpu_model_runner.py:3259] Starting to load model unsloth/Qwen2.5-3B-Instruct-unsloth-bnb-4bit...
INFO 10-09 10:37:06 [cuda.py:377] Using AttentionBackendEnum.FLASHINFER backend.
INFO 10-09 10:37:06 [bitsandbytes_loader.py:791] Loading weights with BitsAndBytes quantization. May take a while ...

model.safetensors:   0%|          | 0.00/2.36G [00:00<?, ?B/s]

INFO 10-09 10:37:24 [weight_utils.py:441] Time spent downloading weights for unsloth/Qwen2.5-3B-Instruct-unsloth-bnb-4bit: 17.632217 seconds
INFO 10-09 10:37:25 [weight_utils.py:481] No model.safetensors.index.json found in remote.

Loading safetensors checkpoint shards:   0% Completed | 0/1 [00:00<?, ?it/s]

Loading safetensors checkpoint shards:   0% Completed | 0/1 [00:00<?, ?it/s]

INFO 10-09 10:37:29 [punica_selector.py:20] Using PunicaWrapperGPU.
INFO 10-09 10:37:30 [gpu_model_runner.py:3338] Model loading took 2.4503 GiB memory and 23.217310 seconds
INFO 10-09 10:37:47 [backends.py:631] Using cache directory: /root/.cache/vllm/torch_compile_cache/e14fdd0fb8/rank_0_0/backbone for vLLM's torch.compile
INFO 10-09 10:37:47 [backends.py:647] Dynamo bytecode transform time: 15.48 s

Unsloth: Compiling kernels: 0it [00:00, ?it/s]

INFO 10-09 10:37:55 [backends.py:251] Cache the graph for dynamic shape for later use

Unsloth: Compiling kernels: 100%|██████████| 6/6 [00:01<00:00,  3.38it/s, triton_poi_fused_add_cat_index_select_mul_split_split_with_sizes_sub_unsqueeze_view_5]
Unsloth: Compiling kernels: 100%|██████████| 6/6 [00:00<00:00, 220.31it/s, triton_poi_fused_add_cat_index_select_mul_split_split_with_sizes_sub_unsqueeze_view_5]
Unsloth: Compiling kernels: 100%|██████████| 6/6 [00:00<00:00, 245.01it/s, triton_poi_fused_add_cat_index_select_mul_split_split_with_sizes_sub_unsqueeze_view_5]
Unsloth: Compiling kernels: 100%|██████████| 6/6 [00:00<00:00, 250.76it/s, triton_poi_fused_add_cat_index_select_mul_split_split_with_sizes_sub_unsqueeze_view_5]
Unsloth: Compiling kernels: 100%|██████████| 6/6 [00:00<00:00, 232.20it/s, triton_poi_fused_add_cat_index_select_mul_split_split_with_sizes_sub_unsqueeze_view_5]
Unsloth: Compiling kernels: 100%|██████████| 6/6 [00:00<00:00, 288.04it/s, triton_poi_fused_add_cat_index_select_mul_split_split_with_sizes_sub_unsqueeze_view_5]
Unsloth: Compiling kernels: 100%|██████████| 6/6 [00:00<00:00, 289.44it/s, triton_poi_fused_add_cat_index_select_mul_split_split_with_sizes_sub_unsqueeze_view_5]
Unsloth: Compiling kernels: 100%|██████████| 6/6 [00:00<00:00, 278.94it/s, triton_poi_fused_add_cat_index_select_mul_split_split_with_sizes_sub_unsqueeze_view_5]
Unsloth: Compiling kernels: 100%|██████████| 6/6 [00:00<00:00, 281.06it/s, triton_poi_fused_add_cat_index_select_mul_split_split_with_sizes_sub_unsqueeze_view_5]
Unsloth: Compiling kernels: 100%|██████████| 6/6 [00:00<00:00, 300.62it/s, triton_poi_fused_add_cat_index_select_mul_split_split_with_sizes_sub_unsqueeze_view_5]
Unsloth: Compiling kernels: 100%|██████████| 6/6 [00:00<00:00, 254.19it/s, triton_poi_fused_add_cat_index_select_mul_split_split_with_sizes_sub_unsqueeze_view_5]
Unsloth: Compiling kernels: 100%|██████████| 6/6 [00:00<00:00, 260.57it/s, triton_poi_fused_add_cat_index_select_mul_split_split_with_sizes_sub_unsqueeze_view_5]
Unsloth: Compiling kernels: 100%|██████████| 6/6 [00:00<00:00, 247.73it/s, triton_poi_fused_add_cat_index_select_mul_split_split_with_sizes_sub_unsqueeze_view_5]
Unsloth: Compiling kernels: 100%|██████████| 6/6 [00:00<00:00, 244.36it/s, triton_poi_fused_add_cat_index_select_mul_split_split_with_sizes_sub_unsqueeze_view_5]
Unsloth: Compiling kernels: 100%|██████████| 6/6 [00:00<00:00, 244.39it/s, triton_poi_fused_add_cat_index_select_mul_split_split_with_sizes_sub_unsqueeze_view_5]
Unsloth: Compiling kernels: 100%|██████████| 6/6 [00:00<00:00, 290.26it/s, triton_poi_fused_add_cat_index_select_mul_split_split_with_sizes_sub_unsqueeze_view_5]
Unsloth: Compiling kernels: 100%|██████████| 6/6 [00:00<00:00, 220.93it/s, triton_poi_fused_add_cat_index_select_mul_split_split_with_sizes_sub_unsqueeze_view_5]
Unsloth: Compiling kernels: 100%|██████████| 6/6 [00:00<00:00, 238.37it/s, triton_poi_fused_add_cat_index_select_mul_split_split_with_sizes_sub_unsqueeze_view_5]
Unsloth: Compiling kernels: 100%|██████████| 6/6 [00:00<00:00, 282.50it/s, triton_poi_fused_add_cat_index_select_mul_split_split_with_sizes_sub_unsqueeze_view_5]
Unsloth: Compiling kernels: 100%|██████████| 6/6 [00:00<00:00, 222.72it/s, triton_poi_fused_add_cat_index_select_mul_split_split_with_sizes_sub_unsqueeze_view_5]
Unsloth: Compiling kernels: 100%|██████████| 6/6 [00:00<00:00, 208.83it/s, triton_poi_fused_add_cat_index_select_mul_split_split_with_sizes_sub_unsqueeze_view_5]
Unsloth: Compiling kernels: 100%|██████████| 6/6 [00:00<00:00, 221.28it/s, triton_poi_fused_add_cat_index_select_mul_split_split_with_sizes_sub_unsqueeze_view_5]
Unsloth: Compiling kernels: 100%|██████████| 6/6 [00:00<00:00, 276.91it/s, triton_poi_fused_add_cat_index_select_mul_split_split_with_sizes_sub_unsqueeze_view_5]
Unsloth: Compiling kernels: 100%|██████████| 6/6 [00:00<00:00, 263.18it/s, triton_poi_fused_add_cat_index_select_mul_split_split_with_sizes_sub_unsqueeze_view_5]
Unsloth: Compiling kernels: 100%|██████████| 6/6 [00:00<00:00, 227.50it/s, triton_poi_fused_add_cat_index_select_mul_split_split_with_sizes_sub_unsqueeze_view_5]
Unsloth: Compiling kernels: 100%|██████████| 6/6 [00:00<00:00, 239.26it/s, triton_poi_fused_add_cat_index_select_mul_split_split_with_sizes_sub_unsqueeze_view_5]
Unsloth: Compiling kernels: 100%|██████████| 6/6 [00:00<00:00, 243.67it/s, triton_poi_fused_add_cat_index_select_mul_split_split_with_sizes_sub_unsqueeze_view_5]
Unsloth: Compiling kernels: 100%|██████████| 6/6 [00:00<00:00, 225.78it/s, triton_poi_fused_add_cat_index_select_mul_split_split_with_sizes_sub_unsqueeze_view_5]
Unsloth: Compiling kernels: 100%|██████████| 6/6 [00:00<00:00, 266.98it/s, triton_poi_fused_add_cat_index_select_mul_split_split_with_sizes_sub_unsqueeze_view_5]
Unsloth: Compiling kernels: 100%|██████████| 6/6 [00:00<00:00, 243.96it/s, triton_poi_fused_add_cat_index_select_mul_split_split_with_sizes_sub_unsqueeze_view_5]
Unsloth: Compiling kernels: 100%|██████████| 6/6 [00:00<00:00, 265.99it/s, triton_poi_fused_add_cat_index_select_mul_split_split_with_sizes_sub_unsqueeze_view_5]
Unsloth: Compiling kernels: 100%|██████████| 6/6 [00:00<00:00, 254.65it/s, triton_poi_fused_add_cat_index_select_mul_split_split_with_sizes_sub_unsqueeze_view_5]
Unsloth: Compiling kernels: 100%|██████████| 6/6 [00:00<00:00, 259.62it/s, triton_poi_fused_add_cat_index_select_mul_split_split_with_sizes_sub_unsqueeze_view_5]
Unsloth: Compiling kernels: 100%|██████████| 6/6 [00:00<00:00, 190.65it/s, triton_poi_fused_add_cat_index_select_mul_split_split_with_sizes_sub_unsqueeze_view_5]
Unsloth: Compiling kernels: 100%|██████████| 6/6 [00:00<00:00, 229.09it/s, triton_poi_fused_add_cat_index_select_mul_split_split_with_sizes_sub_unsqueeze_view_5]
Unsloth: Compiling kernels: 100%|██████████| 3/3 [00:00<00:00, 15.94it/s, triton_red_fused__to_copy_add_mean_mul_pow_rsqrt_2]

INFO 10-09 10:38:13 [backends.py:282] Compiling a graph for dynamic shape takes 24.56 s
INFO 10-09 10:38:24 [monitor.py:34] torch.compile takes 40.04 s in total
INFO 10-09 10:38:24 [topk_topp_sampler.py:36] Using FlashInfer for top-p & top-k sampling.
INFO 10-09 10:40:16 [gpu_worker.py:359] Available KV cache memory: 8.07 GiB
INFO 10-09 10:40:17 [kv_cache_utils.py:1229] GPU KV cache size: 234,912 tokens
INFO 10-09 10:40:17 [kv_cache_utils.py:1234] Maximum concurrency for 1,024 tokens per request: 229.41x
INFO 10-09 10:40:17 [kernel_warmup.py:65] Warming up FlashInfer attention.
INFO 10-09 10:42:54 [vllm_utils.py:841] Unsloth: Running patched vLLM v1 `capture_model`.

Capturing CUDA graphs (mixed prefill-decode, PIECEWISE):   0%|          | 0/30 [00:00<?, ?it/s]

WARNING 10-09 10:42:54 [utils.py:250] Using default LoRA kernel configs

Capturing CUDA graphs (mixed prefill-decode, PIECEWISE): 100%|██████████| 30/30 [00:41<00:00,  1.39s/it]
Capturing CUDA graphs (decode, FULL): 100%|██████████| 18/18 [00:04<00:00,  4.49it/s]

INFO 10-09 10:43:40 [gpu_model_runner.py:4244] Graph capturing finished in 46 secs, took 0.71 GiB
INFO 10-09 10:43:40 [vllm_utils.py:848] Unsloth: Patched vLLM v1 graph capture finished in 46 secs.

INFO 10-09 10:43:42 [core.py:250] init engine (profile, create kv cache, warmup model) took 371.38 seconds
INFO 10-09 10:43:45 [llm.py:352] Supported tasks: ('generate',)

`torch_dtype` is deprecated! Use `dtype` instead!

Unsloth: Just some info: will skip parsing ['post_feedforward_layernorm_1', 'post_per_layer_input_norm', 'input_layernorm', 'post_attention_layernorm', 'post_feedforward_layernorm', 'k_layernorm', 'post_feedforward_layernorm_2', 'post_layernorm', 'layer_norm1', 'q_layernorm', 'pre_feedforward_layernorm', 'q_norm', 'norm', 'k_norm', 'operator_norm', 'norm1', 'ffn_norm', 'layer_norm2', 'pre_feedforward_layernorm_2', 'attention_norm', 'norm2']

Some weights of Qwen2ForCausalLM were not initialized from the model checkpoint at unsloth/Qwen2.5-3B-Instruct-unsloth-bnb-4bit and are newly initialized: ['lm_head.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Performing substitution for additional_keys=set()
Unsloth: Just some info: will skip parsing ['post_feedforward_layernorm_1', 'post_per_layer_input_norm', 'input_layernorm', 'post_attention_layernorm', 'post_feedforward_layernorm', 'k_layernorm', 'post_feedforward_layernorm_2', 'post_layernorm', 'layer_norm1', 'q_layernorm', 'pre_feedforward_layernorm', 'q_norm', 'norm', 'k_norm', 'cross_attn_post_attention_layernorm', 'operator_norm', 'norm1', 'ffn_norm', 'cross_attn_input_layernorm', 'layer_norm2', 'pre_feedforward_layernorm_2', 'attention_norm', 'norm2']

Unsloth 2026.10.3 patched 36 layers with 36 QKV layers, 36 O layers and 36 MLP layers.

### Data Prep
<a name="Data"></a>

We directly leverage [@willccbb](https://gist.github.com/willccbb/4676755236bb08cab5f4e54a0475d6fb) for data prep and all reward functions. You are free to create your own!

In [4]:
import re
from datasets import load_dataset, Dataset

# Load and prep dataset
SYSTEM_PROMPT = """
Respond in the following format:
<reasoning>
...
</reasoning>
<answer>
...
</answer>
"""

XML_COT_FORMAT = """\
<reasoning>
{reasoning}
</reasoning>
<answer>
{answer}
</answer>
"""

def extract_xml_answer(text: str) -> str:
    answer = text.split("<answer>")[-1]
    answer = answer.split("</answer>")[0]
    return answer.strip()

def extract_hash_answer(text: str) -> str | None:
    if "####" not in text:
        return None
    return text.split("####")[1].strip()

# uncomment middle messages for 1-shot prompting
def get_gsm8k_questions(split = "train") -> Dataset:
    data = load_dataset('openai/gsm8k', 'main')[split] # type: ignore
    data = data.map(lambda x: { # type: ignore
        'prompt': [
            {'role': 'system', 'content': SYSTEM_PROMPT},
            {'role': 'user', 'content': x['question']}
        ],
        'answer': extract_hash_answer(x['answer'])
    }) # type: ignore
    return data # type: ignore

dataset = get_gsm8k_questions()

# Reward functions
def correctness_reward_func(prompts, completions, answer, **kwargs) -> list[float]:
    responses = [completion[0]['content'] for completion in completions]
    q = prompts[0][-1]['content']
    extracted_responses = [extract_xml_answer(r) for r in responses]
    print('-'*20, f"Question:\n{q}", f"\nAnswer:\n{answer[0]}", f"\nResponse:\n{responses[0]}", f"\nExtracted:\n{extracted_responses[0]}")
    return [2.0 if r == a else 0.0 for r, a in zip(extracted_responses, answer)]

def int_reward_func(completions, **kwargs) -> list[float]:
    responses = [completion[0]['content'] for completion in completions]
    extracted_responses = [extract_xml_answer(r) for r in responses]
    return [0.5 if r.isdigit() else 0.0 for r in extracted_responses]

def strict_format_reward_func(completions, **kwargs) -> list[float]:
    """Reward function that checks if the completion has a specific format."""
    pattern = r"^<reasoning>\n.*?\n</reasoning>\n<answer>\n.*?\n</answer>\n$"
    responses = [completion[0]["content"] for completion in completions]
    matches = [re.match(pattern, r) for r in responses]
    return [0.5 if match else 0.0 for match in matches]

def soft_format_reward_func(completions, **kwargs) -> list[float]:
    """Reward function that checks if the completion has a specific format."""
    pattern = r"<reasoning>.*?</reasoning>\s*<answer>.*?</answer>"
    responses = [completion[0]["content"] for completion in completions]
    matches = [re.match(pattern, r) for r in responses]
    return [0.5 if match else 0.0 for match in matches]

def count_xml(text) -> float:
    count = 0.0
    if text.count("<reasoning>\n") == 1:
        count += 0.125
    if text.count("\n</reasoning>\n") == 1:
        count += 0.125
    if text.count("\n<answer>\n") == 1:
        count += 0.125
        count -= len(text.split("\n</answer>\n")[-1])*0.001
    if text.count("\n</answer>") == 1:
        count += 0.125
        count -= (len(text.split("\n</answer>")[-1]) - 1)*0.001
    return count

def xmlcount_reward_func(completions, **kwargs) -> list[float]:
    contents = [completion[0]["content"] for completion in completions]
    return [count_xml(c) for c in contents]

README.md: 0.00B [00:00, ?B/s]

main/train-00000-of-00001.parquet:   0%|          | 0.00/2.31M [00:00<?, ?B/s]

main/test-00000-of-00001.parquet:   0%|          | 0.00/419k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/7473 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/1319 [00:00<?, ? examples/s]

Map:   0%|          | 0/7473 [00:00<?, ? examples/s]

<a name="Train"></a>
### Train the model

Now set up GRPO Trainer and all configurations!

In [5]:
from trl import GRPOConfig, GRPOTrainer
training_args = GRPOConfig(
    use_vllm = True, # use vllm for fast inference!
    learning_rate = 5e-6,
    adam_beta1 = 0.9,
    adam_beta2 = 0.99,
    weight_decay = 0.001,
    warmup_ratio = 0.1,
    lr_scheduler_type = "cosine",
    optim = "adamw_8bit",
    logging_steps = 1,
    per_device_train_batch_size = 1,
    gradient_accumulation_steps = 1, # Increase to 4 for smoother training
    num_generations = 8, # Decrease if out of memory
    max_prompt_length = 256,
    max_completion_length = 200,
    # num_train_epochs = 1, # Set to 1 for a full training run
    max_steps = 250,
    save_steps = 250,
    max_grad_norm = 0.1,
    report_to = "none", # Can use Weights & Biases
    output_dir = "outputs",
)

Unsloth: GRPO now defaults to TRL's loss_type = 'dapo' with beta = 0.0. Set loss_type = 'bnpo', beta = 0.001 for Unsloth's previous default.
Unsloth: We now expect `per_device_train_batch_size` * `gradient_accumulation_steps` * `world_size` to be a multiple of `num_generations`.
We will change the batch size of 1 to the `num_generations` of 8

And let's run the trainer! If you scroll up, you'll see a table of rewards. The goal is to see the `reward` column increase!

You might have to wait 150 to 200 steps for any action. You'll probably get 0 reward for the first 100 steps. Please be patient!

| Step | Training Loss | reward    | reward_std | completion_length | kl       |
|------|---------------|-----------|------------|-------------------|----------|
| 1    | 0.000000      | 0.125000  | 0.000000   | 200.000000        | 0.000000 |
| 2    | 0.000000      | 0.072375  | 0.248112   | 200.000000        | 0.000000 |
| 3    | 0.000000      | -0.079000 | 0.163776   | 182.500000        | 0.000005 |

In [6]:
trainer = GRPOTrainer(
    model = model,
    processing_class = tokenizer,
    reward_funcs = [
        xmlcount_reward_func,
        soft_format_reward_func,
        strict_format_reward_func,
        int_reward_func,
        correctness_reward_func,
    ],
    args = training_args,
    train_dataset = dataset,
)
trainer.train()

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 7,473 | Num Epochs = 1 | Total steps = 250
O^O/ \_/ \    Batch size per device = 8 | Gradient accumulation steps = 1
\        /    Data Parallel GPUs = 1 | Total batch size (8 x 1 x 1) = 8
 "-____-"     Trainable parameters = 119,734,272 of 3,205,672,960 (3.74% trained)

WARNING 10-09 10:44:03 [processor.py:246] vLLM has deprecated support for supporting different tokenizers for different LoRAs. By default, vLLM uses base model's tokenizer. If you are using a LoRA with its own tokenizer, consider specifying `--tokenizer [lora_path]` to use the LoRA tokenizer.
-------------------- Question:
A concert ticket costs $40. Mr. Benson bought 12 tickets and received a 5% discount for every ticket bought that exceeds 10. How much did Mr. Benson pay in all?
Answer:
476
Response:
<reasoning>
We need to calculate the total cost of the concert tickets that Mr. Benson bought, considering the 5% discount for each ticket after the first 10 tickets are paid at full price. The first 10 tickets are priced at $40 each, and the remaining 2 tickets will get a 5% discount on their base price of $40.

- Calculate the cost for the first 10 tickets: \(10 \times 40 = 400\).
- Calculate the discounted cost for the remaining 2 tickets: \(2 \times (40 \times 0.95) = 2 \times 38 = 76\).
- Summing these amounts gives the total cost: \(400 + 76 = 476\).

</reasoning>
<answer>
Mr. Benson paid a total of $476 for the concert tickets.
</answer>
Extracted:
Mr. Benson paid a total of $476 for the concert tickets.
Unsloth: Will smartly offload gradients to save VRAM!

-------------------- Question:
Jane is trying to decide whether to buy a house or a trailer. A house costs $480,000 and a trailer costs $120,000. Each loan will be paid in monthly installments over 20 years. How much more is the monthly payment on the house compared to the trailer?
Answer:
1500
Response:
<reasoning>
To determine how much more Jane's monthly payment would be for a house compared to a trailer, we need to calculate the monthly payments for both options separately.

The formula to calculate the monthly installment (M) for a loan is:
\[ M = \frac{P \cdot r \cdot (1 + r)^n}{(1 + r)^n - 1} \]
where:
- \( P \) is the principal amount,
- \( r \) is the monthly interest rate,
- \( n \) is the total number of installments (in months).

However, since the interest rate is not provided, we'll use the commonly used simple interest formula for comparing the payments based on the total interest paid over the life of the loan:
\[ \text{Monthly Payment} = \frac{\text{Total Cost}}{20 \text{ years} \times 12 \text{ months/year}} \]

Given:
- Cost of the
Extracted:
<reasoning>
To determine how much more Jane's monthly payment would be for a house compared to a trailer, we need to calculate the monthly payments for both options separately.

The formula to calculate the monthly installment (M) for a loan is:
\[ M = \frac{P \cdot r \cdot (1 + r)^n}{(1 + r)^n - 1} \]
where:
- \( P \) is the principal amount,
- \( r \) is the monthly interest rate,
- \( n \) is the total number of installments (in months).

However, since the interest rate is not provided, we'll use the commonly used simple interest formula for comparing the payments based on the total interest paid over the life of the loan:
\[ \text{Monthly Payment} = \frac{\text{Total Cost}}{20 \text{ years} \times 12 \text{ months/year}} \]

Given:
- Cost of the
Unsloth: Double buffering enabled (parallel H2D + compute) for backward pass.
-------------------- Question:
Janet pays $40/hour for 3 hours per week of clarinet lessons and $28/hour for 5 hours a week of piano lessons. How much more does she spend on piano lessons than clarinet lessons in a year?
Answer:
1040
Response:
<reasoning>
To find out how much more Janet spends on piano lessons compared to clarinet lessons in a year, we need to calculate the total cost of lessons for both piano and clarinet separately. Then, we subtract the total cost of clarinet lessons from the total cost of piano lessons.
First, let's calculate the weekly cost of clarinet lessons. Janet pays $40 per hour and has 3 hours of lessons per week. Therefore, her weekly cost for clarinet lessons is $40 * 3 = $120.
Next, we calculate the weekly cost of piano lessons. She pays $28 per hour and has 5 hours of lessons per week. Thus, her weekly cost for piano lessons is $28 * 5 = $140.
Now, since we need to find out the difference between the total yearly cost of piano lessons and clarinet lessons, we estimate the weekly difference to be $120 - $140
Extracted:
<reasoning>
To find out how much more Janet spends on piano lessons compared to clarinet lessons in a year, we need to calculate the total cost of lessons for both piano and clarinet separately. Then, we subtract the total cost of clarinet lessons from the total cost of piano lessons.
First, let's calculate the weekly cost of clarinet lessons. Janet pays $40 per hour and has 3 hours of lessons per week. Therefore, her weekly cost for clarinet lessons is $40 * 3 = $120.
Next, we calculate the weekly cost of piano lessons. She pays $28 per hour and has 5 hours of lessons per week. Thus, her weekly cost for piano lessons is $28 * 5 = $140.
Now, since we need to find out the difference between the total yearly cost of piano lessons and clarinet lessons, we estimate the weekly difference to be $120 - $140
-------------------- Question:
Sabrina is collecting herbs to make a poultice for her grandmother. She needs twice as many basil leaves as sage leaves and 5 fewer sage leaves than verbena leaves. If she needs 12 basil leaves, how many leaves total does she need?
Answer:
29
Response:
<reasoning>
Sabrina requires twice as many basil leaves as sage leaves. Given she needs 匹 basil leaves, we can find out the number of sage leaves by setting up the equation:
\[ \text{Number of Basil leaves} = 2 \times \text{Number of Sage leaves} \]
Since the number of basil leaves is 12, we can express the number of sage leaves as:
\[ 12 = 2 \times \text{Number of Sage leaves} \]
Solving for the number of sage leaves, we find that
\[ \text{Number of Sage leaves} = \frac{12}{2} = 6 \]
She also needs 5 fewer sage leaves than verbena leaves, thus we set up the equation:
\[ \text{Number of Sage leaves} = \text{Number of Verbena leaves} - 5 \]
Since the number of sage leaves is 6, we can express the number of
Extracted:
<reasoning>
Sabrina requires twice as many basil leaves as sage leaves. Given she needs 匹 basil leaves, we can find out the number of sage leaves by setting up the equation:
\[ \text{Number of Basil leaves} = 2 \times \text{Number of Sage leaves} \]
Since the number of basil leaves is 12, we can express the number of sage leaves as:
\[ 12 = 2 \times \text{Number of Sage leaves} \]
Solving for the number of sage leaves, we find that
\[ \text{Number of Sage leaves} = \frac{12}{2} = 6 \]
She also needs 5 fewer sage leaves than verbena leaves, thus we set up the equation:
\[ \text{Number of Sage leaves} = \text{Number of Verbena leaves} - 5 \]
Since the number of sage leaves is 6, we can express the number of
-------------------- Question:
Over the past five years, on July 4th, the high temperature for Washington, DC has been: 90 degrees in 2020, 90 degrees in 2019, 90 degrees in 2018, 79 degrees in 2017 and 71 degrees in 2016. What is the average temperature for July 4th in Washington, DC over the past 5 years?
Answer:
84
Response:
<reasoning>
To find the average temperature over the past 5 years, we need to add up all the temperatures and then divide by the number of years (which is 5 in this case).

Given temperatures:
- 90 degrees (2020)
- 90 degrees (2019)
- 90 degrees (2018)
- 79 degrees (2017)
- 71 degrees (2016)

First, we add all the temperatures:
90 + 90 + 90 + 79 + 71 = 410 degrees

Then, to find the average, we divide the sum by the number of years:
410 degrees ÷ 5 years = 82 degrees

The average temperature for July 4th in Washington, DC over the past 5 years is 82 degrees.
</reasoning>
<answer>
82 degrees
</
Extracted:
82 degrees
</
-------------------- Question:
Rene can finish reading 30 pages in 60 minutes. Lulu can read 27 pages in 60 minutes and Cherry can read 25 pages in 60 minutes. If they have been reading for 240 minutes now, how many pages have they finished reading in total?
Answer:
328
Response:
<reasoning>
First, we need to determine the reading speed of each person per minute, and then calculate the number of pages they have read in 240 minutes.

- Rene's reading speed: 30 pages / 60 minutes = 0.5 pages per minute
- Lulu's reading speed: 27 pages / 60 minutes = 0.45 pages per minute
- Cherry's reading speed: 25 pages / 60 minutes = 0.4167 pages per minute

Next, let's calculate the number of pages each person has read in 240 minutes:

- Rene reads: 0.5 pages per minute * 240 minutes = 120 pages
- Lulu reads: 0.45 pages per minute * 240 minutes = 108 pages
- Cherry reads: 0.4167 pages per minute * 2
Extracted:
<reasoning>
First, we need to determine the reading speed of each person per minute, and then calculate the number of pages they have read in 240 minutes.

- Rene's reading speed: 30 pages / 60 minutes = 0.5 pages per minute
- Lulu's reading speed: 27 pages / 60 minutes = 0.45 pages per minute
- Cherry's reading speed: 25 pages / 60 minutes = 0.4167 pages per minute

Next, let's calculate the number of pages each person has read in 240 minutes:

- Rene reads: 0.5 pages per minute * 240 minutes = 120 pages
- Lulu reads: 0.45 pages per minute * 240 minutes = 108 pages
- Cherry reads: 0.4167 pages per minute * 2
-------------------- Question:
Martin rings the small bell 4 times more than 1/3 as often as the big bell. If he rings both of them a combined total of 52 times, how many times does he ring the big bell?
Answer:
36
Response:
<reasoning>
Let's denote the number of times Martin rings the big bell as B and the number of times he rings the small bell as S.

From the problem statement:
1. S = (1/3)*B + 4 (Martin rings the small bell 4 times more than 1/3 as often as the big bell)
2. S + B = 52 (They ring a combined total of 52 times)

We can use the above two equations to find out the value of B (big bell ringings).

First, substitute the expression for S from the first equation into the second equation:
(1/3)*B + 4 + B = 52

Now combine like terms:
(1/3)*B + B = 52 - 4
(1/3 + 1)*B = 48  (Combining the B's in the left side)
(4/3)*B = 48
Extracted:
<reasoning>
Let's denote the number of times Martin rings the big bell as B and the number of times he rings the small bell as S.

From the problem statement:
1. S = (1/3)*B + 4 (Martin rings the small bell 4 times more than 1/3 as often as the big bell)
2. S + B = 52 (They ring a combined total of 52 times)

We can use the above two equations to find out the value of B (big bell ringings).

First, substitute the expression for S from the first equation into the second equation:
(1/3)*B + 4 + B = 52

Now combine like terms:
(1/3)*B + B = 52 - 4
(1/3 + 1)*B = 48  (Combining the B's in the left side)
(4/3)*B = 48
-------------------- Question:
Bert fills out the daily crossword puzzle in the newspaper every day. He uses up a pencil to fill out the puzzles every two weeks. On average, it takes him 1050 words to use up a pencil. How many words are in each crossword puzzle on average?
Answer:
75
Response:
<reasoning>
To find out how many words are in each crossword puzzle on average, we need to determine the total word count of the crossword puzzles Bert meets in two weeks and then divide this by the number of puzzles he completes.

Firstly, Bert uses one pencil every two weeks, and it takes 1050 words to use up one pencil. Assuming Bert solves one crossword puzzle per day, the number of puzzles he does in two weeks (14 days) is equal to the number of days in two weeks.

So, the total word count for the puzzles he completes in two weeks = 1050 words.

Next, we divide this total by the number of days to find the average number of words in each crossword puzzle:
\[
\text{Words per puzzle} = \frac{1050 \text{ words}}{14 \text{ days}}
\]

By performing the division, we obtain:
\[
\frac{10
Extracted:
<reasoning>
To find out how many words are in each crossword puzzle on average, we need to determine the total word count of the crossword puzzles Bert meets in two weeks and then divide this by the number of puzzles he completes.

Firstly, Bert uses one pencil every two weeks, and it takes 1050 words to use up one pencil. Assuming Bert solves one crossword puzzle per day, the number of puzzles he does in two weeks (14 days) is equal to the number of days in two weeks.

So, the total word count for the puzzles he completes in two weeks = 1050 words.

Next, we divide this total by the number of days to find the average number of words in each crossword puzzle:
\[
\text{Words per puzzle} = \frac{1050 \text{ words}}{14 \text{ days}}
\]

By performing the division, we obtain:
\[
\frac{10
-------------------- Question:
Matt can make a batch of a dozen cookies using 2 pounds of flour.  He uses 4 bags of flour each weighing 5 pounds.  If Jim eats 15 cookies how many cookies are left?
Answer:
105
Response:
<reasoning>
First, let's determine the total amount of flour Matt has. He uses 4 bags of flour, each weighing 5 pounds.
Total flour = 4 * 5 = 20 pounds of flour.

Next, calculate the total number of cookies he can make with 20 pounds of flour. We know that he can make a batch of a dozen (12) cookies with 2 pounds of flour. We need to find how many batches he can make with 20 pounds.
Number of batches = 20 pounds / 2 pounds per batch = 10 batches.
Since each batch makes 12 cookies, the total number of cookies he can make is:
Total cookies = 10 batches * 12 cookies per batch = 120 cookies.
Jim ate 15 cookies, we need to find out how many cookies are left.
Cookies left = Total cookies - Jim's cookies = 120 -
Extracted:
<reasoning>
First, let's determine the total amount of flour Matt has. He uses 4 bags of flour, each weighing 5 pounds.
Total flour = 4 * 5 = 20 pounds of flour.

Next, calculate the total number of cookies he can make with 20 pounds of flour. We know that he can make a batch of a dozen (12) cookies with 2 pounds of flour. We need to find how many batches he can make with 20 pounds.
Number of batches = 20 pounds / 2 pounds per batch = 10 batches.
Since each batch makes 12 cookies, the total number of cookies he can make is:
Total cookies = 10 batches * 12 cookies per batch = 120 cookies.
Jim ate 15 cookies, we need to find out how many cookies are left.
Cookies left = Total cookies - Jim's cookies = 120 -
-------------------- Question:
James decides to build a tin house by collecting 500 tins in a week. On the first day, he collects 50 tins. On the second day, he manages to collect 3 times that number. On the third day, he collects 50 tins fewer than the number he collected on the second day. If he collects an equal number of tins on the remaining days of the week, what's the number of tins he collected each day for the rest of the week?
Answer:
50
Response:
<reasoning>
To determine the number of tins James collected each day for the rest of the week, we need to follow several steps to establish how many tins he has sold in total for the week and then evenly distribute the remaining tins over the next four days.

On the first day, James collects 50 tins.
On the second day, he collects 3 * 50 = 150 tins.
On the third day, he collects 150 - 50 = 100 tins.

Adding tins collected in the first three days: 50 (first day) + 150 (second day) + 100 (third day) = 300 tins.

The total target for the week is 500 tins, so the remaining tins to be collected over the next four days is: 500 - 300 = 200 t
Extracted:
<reasoning>
To determine the number of tins James collected each day for the rest of the week, we need to follow several steps to establish how many tins he has sold in total for the week and then evenly distribute the remaining tins over the next four days.

On the first day, James collects 50 tins.
On the second day, he collects 3 * 50 = 150 tins.
On the third day, he collects 150 - 50 = 100 tins.

Adding tins collected in the first three days: 50 (first day) + 150 (second day) + 100 (third day) = 300 tins.

The total target for the week is 500 tins, so the remaining tins to be collected over the next four days is: 500 - 300 = 200 t
-------------------- Question:
A jar of jellybeans has 14 blue jellybeans, 26 purple jellybeans and 40 orange jellybeans. If there are 200 jellybeans in the jar, how many are there of the red color?
Answer:
120
Response:
<reasoning>
We know the total number of jellybeans in the jar is  il "><'b0, and we have the quantities of the three colors mentioned (14 blue, 26 purple, and 40 orange jellybeans). To find out how many red jellybeans there are, we can subtract the combined quantity of the blue, purple, and orange jellybeans from the total number of jellybeans in the jar.

\[
\text{Total jellybeans} = 200
\]

\[
\text{Blue jelly beans} = 14
\]

\[
\text{Purple jelly beans} = 26
\]

\[
\text{Orange jelly beans} = 40
\]

The amount of red jellybeans would be:
\[
\text{Red jelly beans} = \text{Total jellybeans} - (\text{Blue jelly beans} + \text{Purple jelly beans} + \text{
Extracted:
<reasoning>
We know the total number of jellybeans in the jar is  il "><'b0, and we have the quantities of the three colors mentioned (14 blue, 26 purple, and 40 orange jellybeans). To find out how many red jellybeans there are, we can subtract the combined quantity of the blue, purple, and orange jellybeans from the total number of jellybeans in the jar.

\[
\text{Total jellybeans} = 200
\]

\[
\text{Blue jelly beans} = 14
\]

\[
\text{Purple jelly beans} = 26
\]

\[
\text{Orange jelly beans} = 40
\]

The amount of red jellybeans would be:
\[
\text{Red jelly beans} = \text{Total jellybeans} - (\text{Blue jelly beans} + \text{Purple jelly beans} + \text{
-------------------- Question:
Five adults and two children go to see a movie and buy $12 worth of concessions. The total cost of their trip is $76. If each child's ticket is $7, how much, in dollars, are the adult tickets?
Answer:
10
Response:
<reasoning>
Let's identify the known quantities first:
- There are 5 adults and 2 children.
- The concessions cost $12.
- The total cost for the movie and concessions is $76.
- Each child's ticket costs $7.

Let the cost of an adult ticket be \(A \) dollars.

The cost of all child tickets combined is \(2 \times 7 = 14 \) dollars.

The total cost of the movie and concessions, without the adult tickets, would be the $12 for concessions plus the $14 for child tickets, which sums to $26. With the total cost being $76, the adult tickets must make up the difference of \( 76 - 26 = 50 \) dollars. Since there are 5 adult tickets, we can find the cost of each adult ticket by dividing $50 by 5.

\[
\text{Average cost of each adult ticket}
Extracted:
<reasoning>
Let's identify the known quantities first:
- There are 5 adults and 2 children.
- The concessions cost $12.
- The total cost for the movie and concessions is $76.
- Each child's ticket costs $7.

Let the cost of an adult ticket be \(A \) dollars.

The cost of all child tickets combined is \(2 \times 7 = 14 \) dollars.

The total cost of the movie and concessions, without the adult tickets, would be the $12 for concessions plus the $14 for child tickets, which sums to $26. With the total cost being $76, the adult tickets must make up the difference of \( 76 - 26 = 50 \) dollars. Since there are 5 adult tickets, we can find the cost of each adult ticket by dividing $50 by 5.

\[
\text{Average cost of each adult ticket}
-------------------- Question:
Janelle had 26 green marbles. Then she bought 6 bags of blue marbles. There were 10 marbles in each bag.  She created a gift of 6 green marbles and 8 blue marbles and gave it to a friend. How many marbles does Janelle have now?
Answer:
72
Response:
<reasoning>
Janelle starts with 26 green marbles. Then she buys 6 bags of blue marbles, with 10 marbles in each bag. The total number of blue marbles she bought can be calculated by 6 * 镯10 = 60 blue marbles.

She created a gift containing 6 green marbles and 8 blue marbles, so the gift used 6 + 8 = 14 marbles in total. This means there are 3 marbles less (26 - 6) for the remaining green marbles and 22 blue marbles (60 - 8) for the remaining blue marbles left.

To find the total number of marbles she has now, we will add the remaining green and blue marbles: 3 (remaining green marbles) + 22 (remaining blue marbles) = 25 marbles.

</reasoning>
<answer
Extracted:
<reasoning>
Janelle starts with 26 green marbles. Then she buys 6 bags of blue marbles, with 10 marbles in each bag. The total number of blue marbles she bought can be calculated by 6 * 镯10 = 60 blue marbles.

She created a gift containing 6 green marbles and 8 blue marbles, so the gift used 6 + 8 = 14 marbles in total. This means there are 3 marbles less (26 - 6) for the remaining green marbles and 22 blue marbles (60 - 8) for the remaining blue marbles left.

To find the total number of marbles she has now, we will add the remaining green and blue marbles: 3 (remaining green marbles) + 22 (remaining blue marbles) = 25 marbles.

</reasoning>
<answer
-------------------- Question:
Every day in a week, Siena bookmarks 30 website pages from the research she does on her browser. If Siena has 400 bookmarked pages on her bookmarks library now, how many pages will she have in her bookmarks library at the end of March?
Answer:
1330
Response:
<reasoning>

-------------------- Question:
Claudia offers art classes to kids and charges $10.00 for her one-hour class.  If 20 kids attend Saturday’s class and half that many attend Sunday’s class, how much money does she make?
Answer:
300
Response:
<reasoning>
Claudia charges $10.00 per kid for the class. On Saturday, 20 kids attend, so she earns \(20 \times 10 = 200\) dollars. On Sunday, half as many kids attend, which means 10 kids attend. Hence, she earns \(10 \times 10 = 100\) dollars. The total earnings from both days are \(200 + 100 = 300\) dollars.
</reasoning>
<answer>300</answer>
Extracted:
300
-------------------- Question:
Wes wants to place a large planter pot at each corner of his rectangle-shaped pool.  Each planter will have a large palm fern that is $15.00 per plant, 4 creeping jennies that costs $4.00 per plant and 4 geraniums that cost $3.50 per plant.  How much will it cost to fill all the pots?
Answer:
180
Response:
<reasoning>
Wes wants to place the planter pots at the corners of his pool, but the problem does not specify the number of corners (which would be 4 for a rectangle-shaped pool). Regardless of the number of corners, the cost of filling each pot is the same. The cost for one pot includes 15.00 for a palm fern, 4 creeping jennies at 4.00 each, and 4 geraniums at 3.50 each. So, the cost for one pot is calculated as follows: \(15 + (4 \times 4.00) + (4 \times 3.50) = 15 + 16 + 14 = 45\). Since there are 4 pots, the total cost is \(4 \times 45 = 180\).
</reasoning>
<answer>180</answer>
Extracted:
180
-------------------- Question:
Matt rode his bike away from the house, he rode a total of 1000 feet.  Along the way, he passed a stop sign that was 350 feet away from his house.  He continued his ride and passed a second sign.  After passing the second sign he road an additional 275 feet.  How many feet are between the first and second signs?
Answer:
375
Response:
<reasoning>
Matt rode a total of 野1000 feet. He passed a stop sign at 350 feet, and then rode an additional 275 feet after passing the second sign. This means he rode 1000 - 275 = 725 feet up to the second sign. Since the first sign was at 350 feet, the distance between the first and second signs is 725 - 350 = 375 feet.
</reasoning>
<answer>375</answer>
Extracted:
375
-------------------- Question:
Melissa sells a coupe for $30,000 and an SUV for twice as much. If her commission is 2%, how much money did she make from these sales?
Answer:
1800
Response:
<reasoning>
Melissa sells the SUV for 2 * $30,000 = $60,000. The total sale amount is $30,000 + $60,000 = $90,000. With a 2% commission, she makes 0.02 * $90,000 = $1,800 from these sales.
</reasoning>
<answer>$1,800</answer>
Extracted:
$1,800
-------------------- Question:
Luther made 12 pancakes for breakfast. His family has 8 people. How many more pancakes must he make for everyone to have a second pancake?
Answer:
4
Response:
<reasoning>
Luther made 格 pancakes. His family has 8 people. To have a second pancake, each of the 8 people in the family should have 2 pancakes. So, in total, for 8 people to have 2 pancakes each, they would need 8 * 2 = 16 pancakes. Since Luther already made 12 pancakes, he needs to make 16 - 12 = 4 more pancakes.
</reasoning>
<answer>4</answer>
Extracted:
4
-------------------- Question:
John has to restring 3 basses with 4 strings each, twice as many guitars which have 6 strings each, and 3 fewer 8 string guitars than the normal guitars.  How many strings does he need?
Answer:
72
Response:
<reasoning>
John needs to restring 3 basses with 4 strings each, which is 3 * 4 = 12 strings for the basses. He needs to do this twice, so 12 * 2 = 24 strings for the basses. He has twice as many guitars as basses, so he will play 3 * 2 = 6 guitars. For one guitar with 6 strings, he needs 6 strings, and he will play 6 * 6 = 36 strings for the guitars. He has 3 fewer 8-string guitars than normal guitars, meaning there are 6 - 3 = 3 8-string guitars. This means he needs 3 * 8 = 24 strings for the guitars. Hence, the total number of strings needed is 12 (for basses) + 36 (for guitars) + 24 (for 8-string guitars) =
Extracted:
<reasoning>
John needs to restring 3 basses with 4 strings each, which is 3 * 4 = 12 strings for the basses. He needs to do this twice, so 12 * 2 = 24 strings for the basses. He has twice as many guitars as basses, so he will play 3 * 2 = 6 guitars. For one guitar with 6 strings, he needs 6 strings, and he will play 6 * 6 = 36 strings for the guitars. He has 3 fewer 8-string guitars than normal guitars, meaning there are 6 - 3 = 3 8-string guitars. This means he needs 3 * 8 = 24 strings for the guitars. Hence, the total number of strings needed is 12 (for basses) + 36 (for guitars) + 24 (for 8-string guitars) =
-------------------- Question:
A person puts $5600 in a bank for two years. Each year he earns interest of 7% of the original amount deposited. How much will this person have in the bank after two years?
Answer:
6384
Response:
<reasoning>
The interest earned each year is 7% of $5600, which is $392. After one year, he will have $5600 + $392 = $5992 in the bank. After the second year, the interest earned will be 7% of $5992, which is $419.44. Adding this to the amount in the bank after the first year, he will have $5992 + $419.44 = $6411.44 in the bank after two years.
</reasoning>
<answer>6411.44</answer>
Extracted:
6411.44
-------------------- Question:
Out of the 200 cookies that Javier baked from the recipe he learned online, his wife took 30%, and his daughter took 40 from the remaining cookies. If he ate half of the remaining cookies, how many cookies did they not eat?
Answer:
50
Response:
<reasoning>
Javier baked 200 cookies. His wife took 30%, which is equivalent to 0.30 * 200 = 60 cookies. After his wife took 60 cookies, 200 - 60 = 140 cookies remained. His daughter took 40 more cookies from the remaining 140, so 140 - 40 = 100 cookies were left. Javier ate half of the remaining 100 cookies, which is 0.5 * 100 = 50 cookies. This means 100 - 50 = 50 cookies were not eaten by Javier. Therefore, the number of cookies not eaten is 50.
</reasoning>
<answer>50</answer>
Extracted:
50
-------------------- Question:
Jess and her family play Jenga, a game made up of 54 stacked blocks in which each player removes one block in turns until the stack falls. The 5 players, including Jess, play 5 rounds in which each player removes one block. In the sixth round, Jess's father goes first. He removes a block, causing the tower to almost fall. Next, Jess tries to remove another block knocking down the tower. How many blocks did the tower have before Jess's turn?
Answer:
28
Response:
<reasoning>
In each round of Jenga, there are 5 players who remove one block each, and in total there are 5 rounds. In the 6th round, Jess's father, along with the 4 other players, removed 4 + 5 = 9 blocks before Jess's turn. Thus, the tower had 54 - 9 = 45 blocks remaining.
</reasoning>
<answer>45</answer>
Extracted:
45
-------------------- Question:
Mary is building a mosaic for her school cafeteria's wall. It will be 10 feet tall and 15 feet long. Each tile she uses is 1 inch square. How many tiles will she need?
Answer:
21600
Response:
<reasoning>
Mary's mosaic will be 10 feet tall and 15 feet long, which translates to 120 inches tall (10 * 12) and 180 inches long (15 * 12). To find the total number of tiles she needs, we multiply the length and height in inches, so 120 * 180 = 21600 tiles.
</reasoning>
<answer>21600</answer>
Extracted:
21600
-------------------- Question:
Ahmed has 8 orange trees and four times as many apple trees in his orchard as Hassan. If Hassan has one apple tree and two orange trees, and they both have only apple and orange trees in their orchards, how many more trees are in Ahmed's orchard than in Hassan's?
Answer:
9
Response:
<reasoning>
Ahmed has four times as many apple trees as Hassan, so he has 4 * 1 = 4 apple trees. Since Hassan has 2 orange trees and Ahmed has 8 orange trees, Ahmed has 8 - 2 = 6 fewer orange trees than Hassan. Therefore, the total number of trees in Ahmed's orchard is 8 + 4 = 12 and Hassan has 1 + 2 = 3 trees. The difference in the number of trees between Ahmed's and Hassan's orchards is 12 - 3 = 9.
</reasoning>
<answer>9</answer>
Extracted:
9
-------------------- Question:
It’s exam season and Tristan has several exams to prepare for. On Monday, he studies for 4 hours then studies for twice this long on Tuesday. On Wednesday, Thursday, and Friday he studies for 3 hours each day. He wants to study for a total of 25 hours over the week and divides the remaining amount of study time evenly between Saturday and Sunday. How many hours does Tristan spend studying on Saturday?
Answer:
2
Response:
<reasoning>
Tristan studies for 4 hours on Monday. On Tuesday, he studies twice as long, which is 8 hours. For Wednesday, Thursday, and Friday, he studies 3 hours each day, totaling 9 hours. So far, he has studied 4 + 8 + 3 + 3 + 3 = 21 hours. Since he plans to study a total of 25 hours over the week, he still needs to study 25 - 21 = 4 hours on Saturday and Sunday combined. He divides this remaining time evenly, so he will study 4 / 2 = 2 hours on Saturday.
</reasoning>
<answer>2</answer>
Extracted:
2
-------------------- Question:
Mr. and Mrs. Hugo went on a road trip. On the first day, they traveled 200 miles. On the second day, they traveled 3/4 as far. On the third day, they traveled 1/2 as many miles as the first two days combined. How many miles did they travel for 3 days?
Answer:
525
Response:
<reasoning>
Mr. and Mrs. Hugo traveled 200 miles on the first day. On the second day, they traveled \( \frac{3}{4} \times 200 = 150 \) miles. For the first two days combined, they traveled \( 200 + 150 = 350 \) miles. On the third day, they traveled half as many miles as the first two days combined, which is \( \frac{1}{2} \times 350 = 175 \) miles. Therefore, the total distance traveled over the three days is \( 200 + 150 + 175 = 525 \) miles.
</reasoning>
<answer>525</answer>
Extracted:
525
-------------------- Question:
Billy's family likes to keep their bicycles stored in the garage when they're not being used.  They own a total of 4 bicycles.  Each bicycle wheel has 10 spokes.  How many spokes are inside the garage?
Answer:
80
Response:
<reasoning>
Billy's family owns 4 bicycles and each bicycle has 2 wheels. So, there are 4 * 2 = 8 bicycle wheels in total. Each wheel has 10 spokes. Thus, the total number of spokes in the garage is 8 * 10 = 80 spokes.
</reasoning>
<answer>80</answer>
Extracted:
80
-------------------- Question:
Beth is a scuba diver.  She is excavating a sunken ship off the coast of a small Caribbean island and she must remain underwater for long periods.  Her primary tank, which she wears when she first enters the water, has enough oxygen to allow her to stay underwater for 2 hours.  She also has several 1-hour supplemental tanks that she takes with her as well as stores on the ocean floor so she can change tanks underwater without having to come up to the surface.  She will need to be underwater for 8 hours.  How many supplemental tanks will she need?
Answer:
6
Response:
<reasoning>
Beth needs to stay underwater for 8 hours. Her primary tank provides oxygen for 2 hours, so she will need additional tanks to cover the remaining 6 hours. Since each supplemental tank lasts for 1 hour, she will need 6 supplemental tanks to complete the full 8 hours.
</reasoning>
<answer>6</answer>
Extracted:
6
-------------------- Question:
A bus has a carrying capacity of 80 people. At the first pickup point, the number of people who entered the bus was 3/5 of its carrying capacity. If there were 50 people at the next pick-up point, how many people could not take the bus because it was full?
Answer:
18
Response:
<reasoning>
The bus has a carrying capacity of 80 people. At the first pickup point, 3/5 of its capacity, which is \( 80 \times \frac{3}{5} = 48 \), got on the bus. So, the bus has a full capacity and already carried 48 people. There were 50 people at the next pick-up point. Since the bus has 80 seats and 48 are already taken, we have \( 80 - 48 = 32 \) empty seats. But since there are 50 people trying to board, reducing the available spots by 50, the number of people who could not take the bus because it was full is \( 50 - 32 = 18 \).
</reasoning>
<answer>18</answer>
Extracted:
18
-------------------- Question:
Sally teaches elementary school and is given $320 to spend on books for her students. A reading book costs $12 and there are 30 students in her class. Unfortunately, if the money she is given by the school to pay for books is not sufficient, she will need to pay the rest out of pocket. How much money does Sally need to pay out of pocket, to buy every student a reading book?
Answer:
40
Response:
<reasoning>
Sally needs to buy Hooks books for 30 students, with each book costing $12. The total cost of the books is \(30 \times 12 = 360\) dollars. Since Sally has only $320, the out-of-pocket cost is \(360 - 320 = 40\) dollars.
</reasoning>
<answer>40</answer>
Extracted:
40
-------------------- Question:
Ed has 2 dogs, 3 cats and twice as many fish as cats and dogs combined. How many pets does Ed have in total?
Answer:
15
Response:
<reasoning>
Ed has a total of 2 + 3 = 5 dogs and cats combined. Therefore, he has 2 * 5 = 10 fish. Adding the number of dogs, cats and fish, Ed has a total of 2 + 3 + 10 = 15 pets.
</reasoning>
<answer>15</answer>
Extracted:
15
-------------------- Question:
Jenny got a 95 on her paper. Jason's grade was 25 points less than Jenny's, and Bob's grade was equal to half of Jason's grade. What was Bob's grade?
Answer:
35
Response:
<reasoning>
Jason's grade was 95 - 25 = 70. Bob's grade was half of Jason's grade, which is 70 / 2 = 35.
</reasoning>
<answer>35</answer>
Extracted:
35
-------------------- Question:
Dylan's mother is throwing a baby shower for her best friend. She is expecting 40 guests, of whom she has cleared the parking lot to park in to, leaving only her car and her husband's jeep in the parking lot. The 40 guests, though, arrive in only 10 cars that they park in the parking lot.  If each car has 4 wheels, how many car wheels are there in the parking lot, including both of Dylan's parent's car wheels?
Answer:
48
Response:
<reasoning>
Given that 10 cars are parked in addition to Dylan's parents' car, there are 12 cars in total parked in the parking lot. Each car has 4 wheels, so the total number of car wheels is 12 * 4 = 48 wheels.
</reasoning>
<answer>48</answer>
Extracted:
48
-------------------- Question:
Daisy’s milk cow provides 16 cups of milk per day.  75% of the milk is consumed by Daisy’s kids.  Daisy uses 50% of the remaining milk to cook with.  How much milk is left over?
Answer:
2
Response:
<reasoning>
Daisy's kids consume 25% of the milk (100% - 75% = 25% left after kids) which means 16 cups × 25% = 4 cups are consumed by her kids. Daisy uses 50% of the remaining 12 cups (16 cups - 4 cups = 12 cups) which means 12 cups × 50% = 6 cups are used for cooking. Therefore, the amount of milk left over is 12 cups (remaining after the kids) - 6 cups (used for cooking) = 6 cups.
</reasoning>
<answer>6</answer>
Extracted:
6
-------------------- Question:
Elsa started the day with 40 marbles.  At breakfast, she lost 3 marbles while playing.  At lunchtime, she gave her best friend Susie 5 marbles.  In the afternoon, Elsa's mom bought her a new bag with 12 marbles.  Susie came back and gave Elsa twice as many marbles as she received at lunch.  How many marbles did Elsa end the day with?
Answer:
54
Response:
<reasoning>
Initially, Elsa had 40 marbles. She lost 3 marbles at breakfast, so she had \(40 - 3 = 37\) marbles. At lunchtime, she gave 5 marbles to Susie, so she had \(37 - 5 = 32\) marbles. In the afternoon, her mom bought her a new bag with 12 marbles, making the total \(32 + 12 = 44\) marbles. Susie then gave Elsa twice as many marbles she received at lunch (which is 5) back, so Susie gave 10 marbles to Elsa, increasing Elsa’s marble count to \(44 + 10 = 54\). Thus, Elsa ended the day with 54 marbles.
</reasoning>
<answer>54</answer>
Extracted:
54
-------------------- Question:
Sami finds 3 spiders in the playground.  Hunter sees 12 ants climbing the wall.  Ming discovers 8 ladybugs in the sandbox, and watches 2 of them fly away. How many insects are remaining in the playground?
Answer:
21
Response:
<reasoning>
Sami's finds do not affect the count of insects in the playground. The total number of insects seen initially by Hunter and Ming can be added together to get the total number before any of the insects leave. Hunter and Ming see 12 ants and 8 ladybugs, which is 12 + 8 = 20 insects. Ming also watched 2 ladybugs fly away, but since the question asks for how many insects are remaining, this information is not needed as the total number remains 20.
</reasoning>
<answer>20</answer>
Extracted:
20
-------------------- Question:
Lucas went to the store with $20 and needed to buy 3 avocados that cost $2 each. How much change does he bring home?
Answer:
14
Response:
<reasoning>
Lucas spends 3 avocados * $2 each = $6. So, the remaining money is $20 - $6 = $14. Hence, the change he brings home is $14.
</reasoning>
<answer>14</answer>
Extracted:
14
-------------------- Question:
Sally reads 10 pages of a book on weekdays and 20 pages on weekends. If it takes 2 weeks for Sally to finish her book, how many pages that book has?
Answer:
180
Response:
<reasoning>
Sally reads 10 pages on each weekday which totals to 5*1惹pages = 50 pages per week. She reads 20 pages on the Saturday and Sunday each weekend which totals to 2*20 = 40 pages per week. Thus, in 2 weeks she reads 2*(50+40)=180 pages. The total number of pages in the book is 180.
</reasoning>
<answer>180</answer>
Extracted:
180
-------------------- Question:
Bob wants to build a pyramid out of legos with 3 levels where the bottom level has 7 legos per side and each level has one less lego per side than the level below it. How many legos total will he need?
Answer:
110
Response:
<reasoning>
Bob's pyramid will have a base layer that is 7 legos per side, a middle layer which will be 6 legos per side, and the top layer which will be 5 legos per side. The total number of legos in the pyramid will be the sum of the squares of the lengths of the sides of each layer. That is, the base layer will contribute \( 7^2 = 49 \) legos, the middle layer will contribute \( 6^2 = 36 \) legos, and the top layer will contribute \( 5^2 = 25 \) legos. The total number of legos needed is \( 49 + 36 + 25 = 110 \).
</reasoning>
<answer>110</answer>
Extracted:
110
-------------------- Question:
Brinley's teacher took the grade six students to the San Diego Zoo to watch and learn about animals. While at the zoo, Brinley counted 100 snakes, 80 arctic foxes, and 20 leopards. She also saw ten times more bee-eaters than leopards, half as many cheetahs as snakes, and twice as many alligators as the total number of Arctic foxes and leopards. What's the total number of animals Brinley counted at the zoo?
Answer:
670
Response:
<reasoning>
Brinley saw 10 bee-eaters (10 * 20 leopards = 10 bee-eaters). The number of cheetahs was 1/2 the number of snakes, which is 50 cheetahs (50 = 1/2 * 100). The number of alligators was twice the number of Arctic foxes and leopards, which is 40 alligators (40 = 2 * (80 + 20)). Adding up all the animals Brinley counted: snakes + arctic foxes + leopards + bee-eaters + cheetahs + alligators = 100 + 80 + 20 + 10 + 50 + 40 = 300 animals.
</reasoning>
<answer>300</answer>
Extracted:
300
-------------------- Question:
Ryan's party was 4 times as huge as Taylor's birthday party. If both parties combined had 240 people, how many people were there at Ryan's party?
Answer:
192
Response:
<reasoning>

TrainOutput(global_step=250, training_loss=0.024552161987278307, metrics={'train_runtime': 6636.0774, 'train_samples_per_second': 0.301, 'train_steps_per_second': 0.038, 'total_flos': 0.0, 'train_loss': 0.024552161987278307})

<a name="Inference"></a>
### Inference
Now let's try the model we just trained! First, let's first try the model without any GRPO trained:

In [7]:
text = tokenizer.apply_chat_template([
    {"role" : "user", "content" : "How many r's are in strawberry?"},
], tokenize = False, add_generation_prompt = True)

from vllm import SamplingParams
sampling_params = SamplingParams(
    temperature = 0.8,
    top_p = 0.95,
    max_tokens = 1024,
)
output = model.fast_generate(
    [text],
    sampling_params = sampling_params,
    lora_request = None,
)[0].outputs[0].text

output

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

'There are 1 r in the word "strawberry."'

And now with the LoRA we just trained with GRPO - we first save the LoRA first!

In [8]:
model.save_lora("grpo_saved_lora")

Now we load the LoRA and test:

In [9]:
text = tokenizer.apply_chat_template([
    {"role" : "system", "content" : SYSTEM_PROMPT},
    {"role" : "user", "content" : "How many r's are in strawberry?"},
], tokenize = False, add_generation_prompt = True)

from vllm import SamplingParams
sampling_params = SamplingParams(
    temperature = 0.8,
    top_p = 0.95,
    max_tokens = 1024,
)
output = model.fast_generate(
    text,
    sampling_params = sampling_params,
    lora_request = model.load_lora("grpo_saved_lora"),
)[0].outputs[0].text

output

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

'<reasoning>\nTo find the number of \'r\'s in the word "strawberry", I will go through the word character by character and count the occurrences of the letter \'r\'. The word "strawberry" has 2 \'r\'s: one in the third position and one in the fifth position. \n</reasoning>\n<answer>2</answer>'

Our reasoning model is much better - it's not always correct, since we only trained it for an hour or so - it'll be better if we extend the sequence length and train for longer!

<a name="Save"></a>
### Saving to float16 for VLLM

We also support saving to `float16` directly. Select `merged_16bit` for float16 or `merged_4bit` for int4. We also allow `lora` adapters as a fallback. Use `push_to_hub_merged` to upload to your Hugging Face account! You can go to https://huggingface.co/settings/tokens for your personal tokens. See [our docs](https://unsloth.ai/docs/basics/inference-and-deployment) for more deployment options.

In [10]:
# Merge to 16bit
if False: model.save_pretrained_merged("qwen_finetune_16bit", tokenizer, save_method = "merged_16bit",)
if False: model.push_to_hub_merged("HF_USERNAME/qwen_finetune_16bit", tokenizer, save_method = "merged_16bit", token = "YOUR_HF_TOKEN")

# Merge to 4bit
if False: model.save_pretrained_merged("qwen_finetune_4bit", tokenizer, save_method = "merged_4bit",)
if False: model.push_to_hub_merged("HF_USERNAME/qwen_finetune_4bit", tokenizer, save_method = "merged_4bit", token = "YOUR_HF_TOKEN")

# Just LoRA adapters
if False:
    model.save_pretrained("qwen_lora")
    tokenizer.save_pretrained("qwen_lora")
if False:
    model.push_to_hub("HF_USERNAME/qwen_lora", token = "YOUR_HF_TOKEN")
    tokenizer.push_to_hub("HF_USERNAME/qwen_lora", token = "YOUR_HF_TOKEN")

### GGUF / llama.cpp Conversion
To save to `GGUF` / `llama.cpp`, we support it natively now! We clone `llama.cpp` and we default save it to `q8_0`. We allow all methods like `q4_k_m`. Use `save_pretrained_gguf` for local saving and `push_to_hub_gguf` for uploading to HF.

Some supported quant methods (full list on our [docs page](https://unsloth.ai/docs/basics/inference-and-deployment/saving-to-gguf)):
* `q8_0` - Fast conversion. High resource use, but generally acceptable.
* `q4_k_m` - Recommended. Uses Q6_K for half of the attention.wv and feed_forward.w2 tensors, else Q4_K.
* `q5_k_m` - Recommended. Uses Q6_K for half of the attention.wv and feed_forward.w2 tensors, else Q5_K.

[**NEW**] To finetune and auto export to Ollama, try our [Ollama notebook](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/Llama3_(8B)-Ollama.ipynb)

In [11]:
# Save to 8bit Q8_0
if False: model.save_pretrained_gguf("qwen_finetune", tokenizer,)
# Remember to go to https://huggingface.co/settings/tokens for a token!
# And change hf to your username!
if False: model.push_to_hub_gguf("HF_USERNAME/qwen_finetune", tokenizer, token = "YOUR_HF_TOKEN")

# Save to 16bit GGUF
if False: model.save_pretrained_gguf("qwen_finetune", tokenizer, quantization_method = "f16")
if False: model.push_to_hub_gguf("HF_USERNAME/qwen_finetune", tokenizer, quantization_method = "f16", token = "YOUR_HF_TOKEN")

# Save to q4_k_m GGUF
if False: model.save_pretrained_gguf("qwen_finetune", tokenizer, quantization_method = "q4_k_m")
if False: model.push_to_hub_gguf("HF_USERNAME/qwen_finetune", tokenizer, quantization_method = "q4_k_m", token = "YOUR_HF_TOKEN")

# Save to multiple GGUF options - much faster if you want multiple!
if False:
    model.push_to_hub_gguf(
        "HF_USERNAME/qwen_finetune", # Change hf to your username!
        tokenizer,
        quantization_method = ["q4_k_m", "q8_0", "q5_k_m",],
        token = "YOUR_HF_TOKEN",
    )

Now, use the `qwen_finetune.Q8_0.gguf` file or `qwen_finetune.Q4_K_M.gguf` file in llama.cpp.

And we're done! If you have any questions on Unsloth, we have a [Discord](https://discord.gg/unsloth) channel! If you find any bugs or want to keep updated with the latest LLM stuff, or need help, join projects etc, feel free to join our Discord!

Some other resources:
1. Train your own reasoning model - Llama GRPO notebook [Free Colab](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/Llama3.1_(8B)-GRPO.ipynb)
2. Saving finetunes to Ollama. [Free notebook](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/Llama3_(8B)-Ollama.ipynb)
3. Llama 3.2 Vision finetuning - Radiography use case. [Free Colab](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/Llama3.2_(11B)-Vision.ipynb)
4. See notebooks for DPO, ORPO, Continued pretraining, conversational finetuning and more on our [documentation](https://unsloth.ai/docs/get-started/unsloth-notebooks)!

<div class="align-center">
  <a href="https://unsloth.ai"><img src="https://github.com/unslothai/unsloth/raw/main/images/unsloth%20new%20logo.png" width="115"></a>
  <a href="https://discord.gg/unsloth"><img src="https://github.com/unslothai/unsloth/raw/main/images/Discord.png" width="145"></a>
  <a href="https://unsloth.ai/docs/"><img src="https://github.com/unslothai/unsloth/blob/main/images/documentation%20green%20button.png?raw=true" width="125"></a>

  Join Discord if you need help + ⭐️ <i>Star us on <a href="https://github.com/unslothai/unsloth">Github</a> </i> ⭐️
</div>

  This notebook and all Unsloth notebooks are licensed [LGPL-3.0](https://github.com/unslothai/notebooks?tab=LGPL-3.0-1-ov-file#readme).